{
	"version": 1512675717,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/v_fundoabertura.png",
		"images/s_menu-sheet0.png",
		"images/s_menu-sheet1.png",
		"images/s_menu-sheet2.png",
		"images/s_titulodojogo-sheet0.png",
		"images/s_menujogo-sheet0.png",
		"images/s_menujogo-sheet1.png",
		"images/s_menujogo-sheet2.png",
		"images/s_aberturadosportais-sheet0.png",
		"images/s_fundobrancoopacomenu-sheet0.png",
		"images/keyboardcomands-sheet0.png",
		"images/b_começar_fase-sheet0.png",
		"images/b_começar_fase-sheet1.png",
		"images/p_rotacionar.png",
		"images/p_fixa.png",
		"images/p_move.png",
		"images/p_transpassar.png",
		"images/s_plataforma_fade-sheet0.png",
		"images/s_organela-sheet0.png",
		"images/s_organela-sheet1.png",
		"images/s_proteina-sheet0.png",
		"images/m_mudificaçãofase-sheet0.png",
		"images/s_confuso-sheet0.png",
		"images/l1-sheet0.png",
		"images/s_portal_g1-sheet0.png",
		"images/s_portal_g2-sheet0.png",
		"images/s_portal_s-sheet0.png",
		"images/s_portall_anafase-sheet0.png",
		"images/s_portall_metafase-sheet0.png",
		"images/s_portall_profase-sheet0.png",
		"images/s_portall_telofase-sheet0.png",
		"images/s_portall_meiose-sheet0.png",
		"images/s_portall_concluirmitose-sheet0.png",
		"images/s_portall_concluirfase-sheet0.png",
		"images/s_portall_refazerfase-sheet0.png",
		"images/s_jogador-sheet0.png",
		"images/s_jogador-sheet1.png",
		"images/s_overlap_push-sheet0.png",
		"images/cc_gate1-sheet0.png",
		"images/sc_centro1-sheet0.png",
		"images/sc_centro1-sheet1.png",
		"images/sc_centro1-sheet2.png",
		"images/sc_desativado_f3-sheet0.png",
		"images/sc_con3-sheet0.png",
		"images/sc_fundo-sheet0.png",
		"images/sc_fundo-sheet1.png",
		"images/sc_objeto_colidir-sheet0.png",
		"images/l3-sheet0.png",
		"images/s_dnabruto1-sheet0.png",
		"images/s_dnaseparado1-sheet0.png",
		"images/s_dnaseparado1-sheet1.png",
		"images/s_dnaseparado2-sheet0.png",
		"images/s_duplicador-sheet0.png",
		"images/l2-sheet0.png",
		"images/f_fundotela_fase1.png",
		"images/s_nucleo-sheet0.png",
		"images/s_faseg1-sheet0.png",
		"images/fundo1.png",
		"images/fundo2.png",
		"images/s_reticulo-sheet0.png",
		"images/s_fases-sheet0.png",
		"images/s_faseg2-sheet0.png",
		"images/profase-sheet0.png",
		"images/anafase-sheet0.png",
		"images/s_fusos1-sheet0.png",
		"images/s_fusos2-sheet0.png",
		"images/s_carioteca-sheet0.png",
		"images/s_carioteca-sheet1.png",
		"images/l4-sheet0.png",
		"images/s_dna_mover-sheet0.png",
		"images/mc_toquedna-sheet0.png",
		"images/particles.png",
		"images/tc_caixa_piscante-sheet0.png",
		"images/l5-sheet0.png",
		"images/s_dna_bruto1-sheet0.png",
		"images/s_stetorcolisão-sheet0.png",
		"images/s_dna_top1-sheet0.png",
		"images/s_dna_top1-sheet1.png",
		"images/s_dna_top1-sheet2.png",
		"images/s_fuso_mover1-sheet0.png",
		"images/s_fuso_mover1-sheet1.png",
		"images/s_fuso_mover2-sheet0.png",
		"images/s_fuso_mover2-sheet1.png",
		"images/s_fuso_mover3-sheet0.png",
		"images/s_fuso_mover3-sheet1.png",
		"images/s_fuso_mover3-sheet2.png",
		"images/s_dna_botton1-sheet0.png",
		"images/s_dna_botton1-sheet1.png",
		"images/s_dna_botton2-sheet0.png",
		"images/s_dna_botton2-sheet1.png",
		"images/l6-sheet0.png",
		"images/s_celula-sheet0.png",
		"images/s_celula-sheet1.png",
		"images/telofase-sheet0.png",
		"images/l7-sheet0.png",
		"images/s_celulaa-sheet0.png",
		"images/s_celulab-sheet0.png",
		"images/s_celulac-sheet0.png",
		"images/cc_gateduplicador-sheet0.png",
		"images/cc_gateduplicador2-sheet0.png",
		"images/l9-sheet0.png",
		"images/l8-sheet0.png",
		"images/celulaanimalbruta-sheet0.png",
		"images/celulaanimalbruta-sheet1.png",
		"images/celulavegetalbruta-sheet0.png",
		"images/nuvem-sheet0.png",
		"images/nuvem-sheet1.png",
		"images/nuvemcorreção-sheet0.png",
		"images/nuvempensamento-sheet0.png",
		"images/correçãopc-sheet0.png",
		"images/nuvemlegenda-sheet0.png",
		"media/alert1.ogg",
		"media/cancel - 5.ogg",
		"media/menu click 3.ogg",
		"media/newachievement1.ogg",
		"media/ok - 1.ogg",
		"media/upgrade1.ogg",
		"media/som abertura dos portais.ogg",
		"media/som de portal.ogg",
		"media/som de pulo.ogg",
		"media/som de queda.ogg",
		"media/som de transpassar.ogg",
		"media/som do duplicador.ogg",
		"media/som dos contatos.ogg",
		"media/som portais 2.ogg",
		"media/musica menu.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"logonova.mp4",
		"fundomenu2.mp4",
		"abertura.mp4",
		"fase-menu dos portais.mp4",
		"fase-menu in game.mp4",
		"fase-menu principal.mp4",
		"fase-1.mp4",
		"fase-2.mp4",
		"fase-3.mp4",
		"animacao fundo menu.mp4",
		"fase-4.mp4",
		"fase-5.mp4",
		"keys.mp4",
		"fase-6.mp4",
		"fase-7.mp4",
		"fase-8.mp4",
		"fase-9.mp4",
		"animacaofinal.mp4"
	]
}